// Display tasks generated by agent

import React from 'react';
import type { UserSkill, OnboardingTask } from '../shared/types';

interface TaskListViewProps {
  skill: UserSkill;
  tasks: OnboardingTask[];
  onStartTask: (task: OnboardingTask) => void;
  onNewSkill: () => void;
}

export function TaskListView({ skill, tasks, onStartTask, onNewSkill }: TaskListViewProps) {
  // Sort tasks by order
  const sortedTasks = [...tasks].sort((a, b) => a.order - b.order);

  return (
    <div className="popup-container">
      <div className="header">
        <h2>{skill.name}</h2>
        <p className="skill-goal">{skill.goal}</p>
        {skill.preferred_sites.length > 0 && (
          <div className="skill-sites">
            <strong>Sites:</strong> {skill.preferred_sites.join(', ')}
          </div>
        )}
      </div>

      <div className="task-list-view">
        <div className="tasks-header">
          <h3>Demonstration Tasks</h3>
          <span className="task-count">{tasks.length} tasks</span>
        </div>

        <div className="tasks">
          {sortedTasks.map((task, idx) => (
            <div key={task.id} className="task-card">
              <div className="task-number">#{idx + 1}</div>
              <div className="task-content">
                <h4 className="task-title">{task.title}</h4>
                <p className="task-description">{task.prompt}</p>
                {task.success_hint && (
                  <p className="task-hint">
                    <strong>Success:</strong> {task.success_hint}
                  </p>
                )}
                {task.risk_level !== 'low' && (
                  <span className={`risk-badge risk-${task.risk_level}`}>
                    {task.risk_level} risk
                  </span>
                )}
              </div>
              <button
                onClick={() => onStartTask(task)}
                className="btn-start"
              >
                Record
              </button>
            </div>
          ))}
        </div>

        <div className="footer-actions">
          <button onClick={onNewSkill} className="btn-secondary">
            Create New Skill
          </button>
        </div>
      </div>
    </div>
  );
}
