from __future__ import annotations

import json
import re
from typing import Any

from app.core.config import settings
from app.models import AgentMessage, AgentProvider, TrainingReport


class AgentHarness:
    async def build_training_report(
        self,
        messages: list[AgentMessage],
        provider: AgentProvider | None = None,
    ) -> TrainingReport:
        selected = provider or settings.agent_provider
        if selected == "gemini":
            try:
                return await self._gemini_report(messages)
            except Exception as exc:
                fallback = self._clod_demo_report(messages)
                fallback.notes.append(f"Gemini provider failed; generated with clod demo fallback: {exc}")
                return fallback
        return self._clod_demo_report(messages)

    def _clod_demo_report(self, messages: list[AgentMessage]) -> TrainingReport:
        text = _conversation_text(messages)
        goal = _last_user_goal(messages) or "Fine-tune a small model for helpful instruction following"
        task_type = _detect_task_type(text)
        mode = "max" if re.search(r"\b(max|best|thorough|production|long)\b", text, re.I) else "short"
        dataset_query = _dataset_query(goal, task_type)

        eval_prompts = _extract_eval_prompts(text)
        if not eval_prompts:
            eval_prompts = _default_eval_prompts(task_type, goal)

        hardware = ">=8GB VRAM preferred, CPU fallback allowed for toy mode"
        if mode == "max":
            hardware = ">=16GB VRAM preferred, CPU fallback only for smoke tests"

        return TrainingReport(
            goal=goal,
            base_model=_detect_base_model(text),
            mode=mode,
            task_type=task_type,
            dataset_query=dataset_query,
            training_method="LoRA SFT",
            eval_prompts=eval_prompts[:5],
            hardware_requirement=hardware,
            provider="clod",
            notes=[
                "Generated by the local CLōD demo harness.",
                "Review dataset license and PII policy before running a real marketplace job.",
            ],
        )

    async def _gemini_report(self, messages: list[AgentMessage]) -> TrainingReport:
        if not settings.gemini_api_key:
            raise RuntimeError("GEMINI_API_KEY is not set")

        import httpx

        prompt = {
            "instruction": (
                "Convert this conversation into a strict JSON TrainingReport with keys "
                "goal, base_model, mode, task_type, dataset_query, training_method, "
                "eval_prompts, hardware_requirement, notes. mode must be short or max."
            ),
            "messages": [message.model_dump() for message in messages],
        }
        url = (
            "https://generativelanguage.googleapis.com/v1beta/models/"
            "gemini-1.5-flash:generateContent"
        )
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(
                url,
                params={"key": settings.gemini_api_key},
                json={"contents": [{"parts": [{"text": json.dumps(prompt)}]}]},
            )
            response.raise_for_status()
            payload = response.json()

        raw_text = payload["candidates"][0]["content"]["parts"][0]["text"]
        data = _parse_json_object(raw_text)
        return TrainingReport(
            goal=data["goal"],
            base_model=data.get("base_model", "Qwen/Qwen3-0.6B"),
            mode=data.get("mode", "short"),
            task_type=data.get("task_type", "instruction-following"),
            dataset_query=data.get("dataset_query", _dataset_query(data["goal"], "instruction-following")),
            training_method=data.get("training_method", "LoRA SFT"),
            eval_prompts=data.get("eval_prompts", [])[:5] or _default_eval_prompts("instruction-following", data["goal"]),
            hardware_requirement=data.get(
                "hardware_requirement",
                ">=8GB VRAM preferred, CPU fallback allowed for toy mode",
            ),
            provider="gemini",
            notes=data.get("notes", []),
        )


def _conversation_text(messages: list[AgentMessage]) -> str:
    return "\n".join(f"{message.role}: {message.content}" for message in messages)


def _last_user_goal(messages: list[AgentMessage]) -> str:
    for message in reversed(messages):
        if message.role == "user" and message.content.strip():
            return message.content.strip()
    return ""


def _detect_task_type(text: str) -> str:
    lowered = text.lower()
    if any(token in lowered for token in ["code", "python", "traceback", "debug", "typescript"]):
        return "code"
    if any(token in lowered for token in ["chat", "assistant", "conversation"]):
        return "chat"
    if any(token in lowered for token in ["write", "copy", "essay", "style", "tone"]):
        return "writing"
    if any(token in lowered for token in ["qa", "question", "domain", "legal", "medical", "finance"]):
        return "domain-qa"
    return "instruction-following"


def _detect_base_model(text: str) -> str:
    match = re.search(r"(Qwen/[A-Za-z0-9.\-_/]+|meta-llama/[A-Za-z0-9.\-_/]+|mistralai/[A-Za-z0-9.\-_/]+)", text)
    if match:
        return match.group(1)
    return "Qwen/Qwen3-0.6B"


def _dataset_query(goal: str, task_type: str) -> str:
    compact_goal = re.sub(r"\s+", " ", goal).strip()
    if task_type == "code":
        return f"{compact_goal} instruction examples debugging code"
    if task_type == "writing":
        return f"{compact_goal} high quality writing instruction dataset"
    if task_type == "domain-qa":
        return f"{compact_goal} question answering dataset"
    return f"{compact_goal} instruction tuning examples"


def _extract_eval_prompts(text: str) -> list[str]:
    prompts: list[str] = []
    for line in text.splitlines():
        cleaned = re.sub(r"^\s*[-*\d.)]+\s*", "", line).strip()
        if cleaned.endswith("?") or cleaned.lower().startswith(("explain", "fix", "write", "answer", "suggest")):
            prompts.append(cleaned)
    return prompts


def _default_eval_prompts(task_type: str, goal: str) -> list[str]:
    if task_type == "code":
        return [
            "Explain why this Python loop has an off-by-one error and provide a fix.",
            "Fix this traceback and identify the likely root cause.",
            "Suggest unit tests for a function that parses user-provided JSON.",
            "Review this short function for edge cases and rewrite it defensively.",
        ]
    if task_type == "writing":
        return [
            "Rewrite this paragraph to be clearer while preserving the author voice.",
            "Draft a concise answer for a skeptical reader.",
            "Turn these rough notes into a polished short memo.",
        ]
    if task_type == "domain-qa":
        return [
            f"Answer a beginner question about {goal} with caveats.",
            "List what information is missing before giving a final answer.",
            "Compare two plausible answers and explain which is better supported.",
        ]
    return [
        f"Follow this instruction related to {goal} and explain your reasoning.",
        "Ask one clarifying question, then provide a useful first answer.",
        "Identify assumptions in the request and produce a concise response.",
    ]


def _parse_json_object(text: str) -> dict[str, Any]:
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.S)
    raw = fenced.group(1) if fenced else text[text.find("{") : text.rfind("}") + 1]
    return json.loads(raw)
